app:
  database:
    type: ${db.type:SQL}
    sql:
#      url: jdbc:mysql://localhost:3306/test_db
#      driverClassName: com.mysql.cj.jdbc.Driver
#      username: identity
#      password: identity123
#      database-platform: org.hibernate.dialect.MySQL8Dialect
      url: jdbc:h2:mem:test_db;MODE=MySQL;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;
      driverClassName: org.h2.Driver
      username: identity
      password: identity123
      database-platform: org.hibernate.dialect.H2Dialect
    mongo:
      host: localhost
      port: 27017
      database: test_db